### ISSUE TITLE
Getting error messages from configuration node

### ISSUE THREAD

**Issue by bummzulu** [jeroenhendricksen/node-red-contrib-openhab3#34]
Hi,
I am running the node on the latest versions of node-red and openhab. In the node red debug window I constantly get these errors:

`"Restarting EventSource (after delay)"`

and

`Error: {"type":"error","status":401,"message":"Unauthorized"}`

Strange thing is that the node itself is working. I can read values from OH items.

**Comment by jeroenhendricksen** [comment]
There are 3 different (technical) ways in which the NodeRED plugin communicates with the OpenHAB server:

1. GET request from NodeRED to OpenHAB's `/rest/items/{item}/state` --> used by the `openhab2-get2` node
2. PUT and POST request from NodeRED to OpenHAB's `/rest/items/{item}/state` endpoint --> used by the `openhab2-out2` node
3. A Server-Sent-Events (SSE)-connection to OpenHAB's (v3) `http://openhab:port/rest/events?topics=smarthome/items` endpoint --> used by the `openhab2-in2`, `openhab2-events2` and `openhab2-monitor2` nodes

Number 3 seems to be non-functional in your case. There could be many reasons for this. What happens when you open `http://openhab:port/rest/events?topics=smarthome/items` from your browser? Does a Server-Sent Events connection stay open en post events back to you? (given that something changes in OpenHAB's items states of course). 
Might some form of proxy or authentication be intervening in your case?

**Comment by bummzulu** [comment]
Thanks for these hints. Somehow embarrassing but the issue has disappeared and I have no clue why. Thanks again for the quick reaction. Appreciate your work!
