### ISSUE TITLE
Response error 404

### ISSUE THREAD

**Issue by fastLion** [jeroenhendricksen/node-red-contrib-openhab3#5]
Hi Jeroen, 
I have an issue with the plugin in conjunction with openhab3. It seems to connect to openhab correctly but when I trigger an process I get an error message in the debug window from node red. I have attached a screenshot from the message. 
Im not family with coding but programming with existing tools, such as Node-Red. Will say, the logic behind I understand but struggling with synatx and structur from different coding languages.
I would like to ask you for some hints what could cause such error message, so that I get an starting point for my research. 
Unfortunately Google is not a big help during the fu...... personalisation of the search result. 
Hope you or somebody else can help me
Jens.
![Bildschirmfoto von 2021-03-23 10-51-57](https://user-images.githubusercontent.com/44084444/112129447-b7014a80-8bc7-11eb-8b54-257433b09de5.png)

**Comment by Pantastisch** [comment]
Got the same issue...

Any support here?

**Comment by jeroenhendricksen** [comment]
Hi there, and sorry for my late reaction, it seems GitHub doesn't notify me of new issues here. I think I've corrected that...

I'm sorry to say, but I need more to reproduce this. This project' source code includes a complete test setup (with the help of docker and docker-compose), including Node-Red with a test-flow, this plugin, OpenHAB2 and OpenHAB3 (with predefined test items and groups). Please see the [main readme](https://github.com/jeroenhendricksen/node-red-contrib-openhab3) for more help on starting that environment. If you can reproduce the problem it in that environment and present me with the corresponding Node-RED flow (which you can export), I'd probably be able to find and maybe even fix the problem.

What maybe could have happened is that you've selected an item, which later disappeared or was removed from OpenHAB3 for some reason. (Are you configuring you configuring your Items via a static configuration or via the UI?)
When the plugin then tries to connect to it, it can't find the Item (any more) and so it throws a 404, which is reported by the openhab2get2 module. The plugin doesn't actively scan for Items that have been removed and I wasn't planning on adding such a "feature" because of the complexity it involves.
