### ISSUE TITLE
openhab2-events2 does not work

### ISSUE THREAD

**Issue by richterger** [jeroenhendricksen/node-red-contrib-openhab3#6]
hi, when I use the openhab2-in2 node I get status updates, but when I use the openhab2-events2 I get nothing. I am running openhab v3 and I just connected a debug node to the openhab2-in2/events2 nodes for testing.
Any idea what's wrong?
Gerald

**Comment by jeroenhendricksen** [comment]
> hi, when I use the openhab2-in2 node I get status updates, but when I use the openhab2-events2 I get nothing. I am running openhab v3 and I just connected a debug node to the openhab2-in2/events2 nodes for testing.
> Any idea what's wrong?
> Gerald

Hi Gerald,

Can you maybe create a screenshot of your setup in Node-RED so I can get a better picture of you test-setup?

The event node was not really my invention, but it was inherited with the original plugin I copied the code from. Personally I've never seen any real use for the events plugin because I can see the exact same events from the `openhab2 monitor` node output number 3, but it should work nevertheless.

I've loaded my test environment described in the project's main readme (which you can do too) and for openhab2 it worked (and I assume for openhab3 it's the same). What might be "wrong" is your assumption that performing an action via the `openhab2-get2` node will cause an event. It won't, because it just "gets" the actual value for an Item. Only when you **change** or **update** an item (see the example below), it will trigger an event because an Item' value was updated or changed and openhab noticed

![Screenshot 2021-04-11 at 20 38 20](https://user-images.githubusercontent.com/32140294/114317048-847fa900-9b06-11eb-8a13-4ed2e601b247.png)

**Comment by jeroenhendricksen** [comment]
You where right after all. The `openhab2 events2` node works with openhab v2, but doesn't with openhab v3. I should have tested the v3 as well, but I didn't until now. Sorry for that! I'm working on a fix.

**Comment by jeroenhendricksen** [comment]
I have released `1.3.5` which should fix this issue. Please let me know if it does.

**Comment by richterger** [comment]
Yes, 1.3.5 works with OpenHAB3! Thanks!
